title: AI Coaching Assistant project
description: The landing page for the ACA project

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 

logo: /assets/img/logos_landing_270_480.png
